### Get Today's tasks
GET http://192.168.1.231:12082/api/todayItems
X-API-Token: {{apiToken}}

### Get Categories/Project
GET http://192.168.1.231:12082/api/categories
X-API-Token: {{apiToken}}

### Get Labels
GET http://192.168.1.231:12082/api/labels
X-API-Token: {{apiToken}}
